# this is a deployment file for ckb testnet

[[cells]]
name = "cluster"
enable_type_id = false
location = { file = "../build/release/cluster" }

# The lock script set to output cells
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x20da6b70dfe59586e89635dbb3adc7aa998e7189"
hash_type = "type"
